### ISSUE TITLE
Needs sound

### ISSUE THREAD

**Issue by darvid** [CastleCorp/anotha.one#1]

**Comment by CastleCorp** [comment]
As in him speaking? What kind of sound are we talking about? Love the idea.

**Comment by darvid** [comment]
Yeah, an audio clip of him actually saying "anotha one"

Alternatively, have clips of every phrase and play them as well.

**Comment by CastleCorp** [comment]
I can do the first part I think. Just have it play that when you click the button. 

The clips of phrases is going to be hard. I don't know where I could find them. Probably too much trouble unfortunately.

**Comment by CastleCorp** [comment]
Sound added to the button click.
